server:
       port: 8888
spring:
       datasource:
              url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
              username: root
              password: abc123
              driver-class-name: com.mysql.cj.jdbc.Driver
              type: com.alibaba.druid.pool.DruidDataSource

              initialSize : 5
              minIdle: 5
              maxActive: 20
              maxWait: 60000
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 300000
              validaionQuery: SELECT 1 FROM DUAL
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true

              filters: stat,wall,log4j
              maxPoolPreparedStatementPerConnectionSize: 20
              useGlobalDataSourceStat: true
              connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMills=500
       servlet:
         multipart:
                enabled: true
                max-file-size: 200MB
                max-request-size: 200MB
msg: hello world!
